package git

import (
	"bytes"
	"context"
	"fmt"
	"os/exec"
	"strings"
)

// GH wraps the GitHub CLI
type GH struct{}

// NewGH creates a new GitHub CLI wrapper
func NewGH() *GH {
	return &GH{}
}

// IsInstalled checks if gh is available
func (g *GH) IsInstalled() bool {
	_, err := exec.LookPath("gh")
	return err == nil
}

// IsAuthenticated checks if gh is authenticated
func (g *GH) IsAuthenticated() bool {
	cmd := exec.Command("gh", "auth", "status")
	return cmd.Run() == nil
}

// Clone clones a repository using gh
func (g *GH) Clone(ctx context.Context, repoURL, branch, dest string) error {
	cmd := exec.CommandContext(ctx, "gh", "repo", "clone", repoURL, dest, "--", "--branch", branch)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("gh repo clone failed: %w: %s", err, stderr.String())
	}

	return nil
}

// CreatePR creates a pull request
func (g *GH) CreatePR(ctx context.Context, dir, baseBranch, headBranch, title, body string) (string, error) {
	cmd := exec.CommandContext(ctx, "gh", "pr", "create",
		"--base", baseBranch,
		"--head", headBranch,
		"--title", title,
		"--body", body,
	)
	cmd.Dir = dir

	output, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("gh pr create failed: %w", err)
	}

	// Output is the PR URL
	return strings.TrimSpace(string(output)), nil
}

// GetPRURL gets the URL for an existing PR
func (g *GH) GetPRURL(ctx context.Context, dir, branch string) (string, error) {
	cmd := exec.CommandContext(ctx, "gh", "pr", "view", branch, "--json", "url", "-q", ".url")
	cmd.Dir = dir

	output, err := cmd.Output()
	if err != nil {
		return "", err
	}

	return strings.TrimSpace(string(output)), nil
}

// BuildPRBody generates the PR description
func BuildPRBody(iterations int, success bool, specPath string, details map[string]string) string {
	var sb strings.Builder

	sb.WriteString("## Summary\n\n")

	if success {
		sb.WriteString(fmt.Sprintf("Completed in %d iterations. All tests passing.\n\n", iterations))
	} else {
		sb.WriteString(fmt.Sprintf("Reached max iterations (%d) without completing. Tests may still be failing.\n\n", iterations))
	}

	if specPath != "" {
		sb.WriteString("## Specification\n\n")
		sb.WriteString(fmt.Sprintf("See: %s\n\n", specPath))
	}

	if !success && len(details) > 0 {
		sb.WriteString("## Current State\n\n")
		for key, value := range details {
			sb.WriteString(fmt.Sprintf("- **%s**: %s\n", key, value))
		}
		sb.WriteString("\n")
	}

	if !success {
		sb.WriteString("## Notes\n\n")
		sb.WriteString("Manual intervention may be needed. Review iteration history for context.\n\n")
	}

	sb.WriteString("---\n")
	sb.WriteString("Generated by Ralph-o-matic\n")

	return sb.String()
}

// BuildPRTitle generates the PR title
func BuildPRTitle(branch string, success bool) string {
	if success {
		return fmt.Sprintf("Ralph-o-matic: %s ✓", branch)
	}
	return fmt.Sprintf("Ralph-o-matic: %s ✗ FAILED", branch)
}
