linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - misspell
    - gocritic
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*database/sql.Tx).Rollback
      - (*encoding/json.Encoder).Encode
      - (*encoding/json.Decoder).Decode
  revive:
    rules:
      - name: exported

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic

run:
  timeout: 5m
